__title__ = 'MeteorTears'
__description__ = 'Even the most boring times in life are limited.'
__url__ = 'https://github.com/xiaoxiaolulu/MeteorTears'
__version__ = '1.0.1'
__author__ = 'Null'
__author_email__ = '546464268@qq.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Null'
