#####################################
# Created By: Null
# Created date: 2019-06-05
# Desc: 登录Demo
#####################################

####################################
# 环境准备&数据清洗
####################################
EnvPreparation:
  setUp: pass
  tearDown: pass

test_login_success:
  # 关联的临时变量文件
  relevant_parameter: [Host]
  # 关联的Sql数据
  relevant_sql: []
  # 是否跳过
  skip: False
  # 用例描述
  description: "登录成功"
  # 请求方式
  method: post
  # 请求路由
  url: ${Host}$/v31/mem/action/login
  # 请求参数
  json:
    AppChannelId: "testmarket"
    schema: "A"
    OS: "ANDROID"
    validCode: "111111"
    loginType: "validCode"
    appName: "atzucheApp"
    OsVersion: "28"
    mobile: "15800873806"
    mem_no: "null"
    IMEI: "866957038129841"
    AndroidId: "79f05a5ad238e896"
    deviceName: "STF-AL00"
    mac: "54B12180B787"
    AppVersion: "98"
    publicToken: "0"
    publicCityCode: "021"
    requestId: "54B12180B7871559714482129"
    PublicLongitude: "121.409095"
    androidID: "79f05a5ad238e896"
    PublicLatitude: "31.172282"
  # 请求头部
  headers:
    Content-Type: application/json; charset=utf-8
    Accept-Encoding: gzip
    User-Agent: Autoyol_80:Android_21|CF336E2B0D0A361E679A6699A38A1576D3013004042034B17B72C7B188
    Accept: application/json;version=3.0;compress=false
  # Response返回体提取的参数
  res_index: [token]
  # 断言
  assert:
    status_code: 200
    resCode: "000000"
    resMsg: "success"
  # 落库校验
  check_db:

test_login_fail:
  relevant_parameter: [Host]
  relevant_sql: []
  skip: False
  description: "登录失败"
  method: post
  url: ${Host}$/v31/mem/action/login
  json:
    AppChannelId: "testmarket"
    schema: "A"
    OS: "ANDROID"
    validCode: "111111"
    loginType: "validCode"
    appName: "atzucheApp"
    OsVersion: "28"
    mobile: "15800873806111111111"
    mem_no: null
    IMEI: "866957038129841"
    AndroidId: "79f05a5ad238e896"
    deviceName: "STF-AL00"
    mac: "54B12180B787"
    AppVersion: 98
    publicToken: "0"
    publicCityCode: "021"
    requestId: "54B12180B7871559714482129"
    PublicLongitude: "121.409095"
    androidID: "79f05a5ad238e896"
    PublicLatitude: "31.172282"
  headers:
    Content-Type: application/json; charset=utf-8
    Accept-Encoding: gzip
    User-Agent: Autoyol_80:Android_21|CF336E2B0D0A361E679A6699A38A1576D3013004042034B17B72C7B188
    Accept: application/json;version=3.0;compress=false
  assert:
    resCode: "100000"
    resMsg: "success"
  res_index: [token]
  check_db:

test_login_skip:
  relevant_parameter: [Host]
  relevant_sql: []
  skip: True
  description: "登录跳过"
  method: post
  url: ${Host}$/v31/mem/action/login
  json:
    AppChannelId: "testmarket"
    schema: "A"
    OS: "ANDROID"
    validCode: "111111"
    loginType: "validCode"
    appName: "atzucheApp"
    OsVersion: "28"
    mobile: "15800873806"
    mem_no: null
    IMEI: "866957038129841"
    AndroidId: "79f05a5ad238e896"
    deviceName: "STF-AL00"
    mac: "54B12180B787"
    AppVersion: 98
    publicToken: "0"
    publicCityCode: "021"
    requestId: "54B12180B7871559714482129"
    PublicLongitude: "121.409095"
    androidID: "79f05a5ad238e896"
    PublicLatitude: "31.172282"
  headers:
    Content-Type: application/json; charset=utf-8
    Accept-Encoding: gzip
    User-Agent: Autoyol_80:Android_21|CF336E2B0D0A361E679A6699A38A1576D3013004042034B17B72C7B188
    Accept: application/json;version=3.0;compress=false
  assert:
    resCode: "000000"
    resMsg: "success"
  res_index: [token]
  check_db:

#####################################
# Created By: Null
# Created date: 2019-06-04
# Desc: 新增落地页分类
#####################################

##############环境准备################
#EnvPreparation:
#  setUp: pass
#  tearDown: pass
#
#############新增落地页分类#############
#test_add_category:
#  relevant_parameter: [Host]
##  skip: False
#  description: "落地页分类新增"
#  method: post
#  url: ${Host}$/admin/landingpage/category/add
#  json:
#    description: 自动化测试数据勿动
#    enabled: 1
#    name:  SEMAUTO
#  headers:
#    Content-Type: application/json; charset=utf-8
#  assert:
#    code: 0
#    message: "操作成功"
#  res_index: [data]

#test_add_category_skipo:
#  relevant_parameter: [Host]
##  skip: True
#  description: "落地页分类跳过"
#  method: post
#  url: ${Host}$/admin/landingpage/category/add
#  json:
#    description: 自动化测试数据勿动
#    enabled: 1
#    name:  SEMAUTO
#  headers:
#    Content-Type: application/json; charset=utf-8
#  res_index: [data]
#  assert:
#    code: 0
#    message: "操作成功"

#test_add_category_fail:
#  relevant_parameter: [Host]
##  skip: False
#  description: "落地页分类新增失败"
#  method: post
#  url: ${Host}$/admin/landingpage/category/add
#  json:
#    description: 自动化测试数据勿动
#    enabled: 1五千万
#    name:  SEMAUTO撒大大撒
#  headers:
#    Content-Type: application/json; charset=utf-8
#  res_index: [data]
#  assert:
#    code: 11231

#EnvPreparation:
#  setUp: pass
#  tearDown: pass
#
#test_login:
#  relevant_parameter: [Host]
#  skip: False
#  description: "登录"
#  method: post
#  url: ${Host}$/api/auth/validatelogin
#  json:
#    Account: 062E4604BD48485AB63DBC16899640EB
#    Password: 75A98A08965D48079F565EA561AF37F6
#    TokenSource: APP2BFE4250D27C443FBBD5FD6D6EA0C631
#  headers:
#    Content-Type: application/json; charset=utf-8
#  res_index: [Token]
#  assert:
#    Status: 1
#    Token: [
#      type,
#      int
#    ]
#  diff:
#      Token: FEC0E38B26F757D8A24B837FA96A34D9719284DD1F3B23975F33B20A6CE8C934
#      ExpiryTime: 636951746810501895
#      Status: 1
#      ErrorCodes: null

#test_upload:
#  skip: False
#  description: "上传文件"
#  method: post
#  url: https://wenku.baidu.com/doc/upload/completefile
#  data:
#    filename: Docker技术入门与实战  第3版@www.java1234.com.pdf
#    identifier: 34c4f9c87f00f0f0b31dfd49ee4742ec
#    totalSize: 168196564
#    file_ext: pdf
#    token: ee90ba4e9f9dd15bb666d4e0536475ce
#  files:
#    file: open(r'C:\Users\56464\Desktop\快速问答模板(1).xlsx', 'rb')
#  headers:
#    Accept-Encoding: gzip, deflate, br
#    Accept-Language: zh-CN,zh;q=0.9
#    Cache-Control: no-cache
#    Connection: keep-alive
#    Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0M5SApIyZxCKVLDW
#    Cookie: BAIDUID=65918B0C69BC04BF80888B173FBE5DEC:FG=1; PSTM=1538993297; BIDUPSID=97C31A35EB8BD710622CF10FC14CF428; MCITY=-70031%3A289%3A; _click_param_pc_rec_doc_2017_testid=4; BDUSS=Jva0VPeVB-eDRvLXVMbWJ4OEhGR1RNSmx3YlFobkpiU1NHcn4tc3JVMnN1TmRjSVFBQUFBJCQAAAAAAAAAAAEAAAA8dYU6xL7EvsS-2LzQocS-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKwrsFysK7BcVF; BDRCVFR[sK1aAlma4-c]=mk3SLVN4HKm; delPer=0; BCLID=7854317556516949430; BDSFRCVID=z2AOJeC629zL-qR9P3C8MoTgYe5ombJTH6aoCXjn6EdMhwqdDul0EG0PHf8g0KubFpqrogKK0eOTHvkF_2uxOjjg8UtVJeC6EG0P3J; H_BDCLCKID_SF=JbFfoC0-tKvbfP0kbRbJq4teheT22jnNQ2J9aJ5nJD_bOfoSQpLB05tbWtcyLPbk5m0tWxcKQpP-HJ7IefQ83P_qMp7BB4nHtgcAKl0MLPblbb0xyn_VXt_t5MnMBMPj5mOnaPQo3fAKftnOM46JehL3346-35543bRTohFLtDKMMKKRj5035n-WqxjK24oyaC6ysJOOaCvGVJvOy4oTj6j-DG_O0jL8Ln7Qbl6OQn3ZeqkGhq6K3MvB-fn2BPcKJHKehnjg-xtWehnFQft20-LbeMtjBbQat664Kb7jWhk2eq72ybjOQlRX5q79atTMfNTJ-qcH0KQpsIJMDUC0D6Q3ja_etT8sb5vfsJQqaRjoDJjvq4bohjPLX-v9BtQmJJu8oDKy3DKBVKO1QMco3--4bt4t2lTHQg-q3R7JWnTHMxIRW-QUKqObb-7B0x-jLITOVn0MW-5DhtjHQPnJyUnQbtnnBn5W3H8HL4nv2JcJbM5m3x6qLTKkQN3TJMIEtJIJ_IKbJIt3fP36q4jHht_ehfQyetJyaR3D_pOvWJ5TMC_wD6_WW-6-0abmKxryQIvk0lkaaxcKShPC-tP5jlOXhR7A-4cfaN4O0pnH3l02Vb59e-t2ynLVDqQ40-RMW20j0l7mWPQOsxA45J7cM4IseboJLfT-0bc4KKJxthF0hC0lj5AMejvMbxQD-4oX-K-X3b7Ef-FKEq7_bf--D6FhX2cDQjcTt2AO2R7m5MTqMJ7z-x6xy5K_hPbvatCq3CnuBP3h5pbhDKJHQT3my-5bbN3i-4jl-T6HWb3cWKJq8UbS54RPBTD02-nBat-OQ6npaJ5nJq5nhMtRy66jK4JKjH_tqToP; pgv_pvi=8864683008; pgv_si=s4810456064; BDORZ=FFFB88E999055A3F8A630C64834BD6D0; BDRCVFR[S_ukKV6dOkf]=mk3SLVN4HKm; PSINO=2; ZD_ENTRY=baidu; H_PS_PSSID=1420_21106_29135_20698_28518_29098_29134_28836_28584_26350_22160; Hm_lvt_d8bfb560f8d03bbefc9bdecafc4a4bf6=1559550293; Hm_lpvt_d8bfb560f8d03bbefc9bdecafc4a4bf6=1559550293; isJiaoyuVip=1
#    Host: wenku.baidu.com
#    Origin: https://wenku.baidu.com
#    Pragma: no-cache
#    Referer: https://wenku.baidu.com/new?fr=home
#    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3676.400 QQBrowser/10.4.3505.400
#  assert:
#    code: 0

#test_upload:
#  relevant_parameter: [Host, Token]
#  skip: False
#  description: "上传文件"
#  method: post
#  url: ${Host}$/api/admin/keyword/KQA/Upload
#  data: '------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"file\"; filename=\"hello.csv\"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"BotId\"\r\n\r\n8e0b6707-bcc6-4c4c-b072-80b169003804\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"TenantDomain\"\r\n\r\nadmin@testbot.hightalk.ai\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"TenantId\"\r\n\r\n928d2511-6783-43c2-bde5-dcf059f55710\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--'
#  headers:
#    Access-Token: ${Token}$
#    Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryapU3GYGLUkbHDEGF
#    User-Agent: "PostmanRuntime/7.13.0"
#    Accept: "*/*"
#    Cache-Control: no-cache
#    Postman-Token: 5fe99c0e-e1b3-431f-94ac-31e5acdf4d77,95f8878b-156a-4d1f-8833-d76d67f3e9b8
#    Host: 192.168.1.104:10033
#    accept-encoding: "gzip, deflate"
#    content-length: "5143"
#    Connection: keep-alive
#    cache-control: no-cache
#  assert:
#    Status: 0
#    ErrorMessage: 导入发生异常请重试！
#  diff:
#    Status: 0
#    ErrorCodes: [
#      {
#        ErrorCode: "",
#        ErrorMessage: "Missing content-type boundary."
#      }
#      ]
#    Data: 0
