CONTENT:
  lib/templates/content
HEADER:
  lib/templates/header
EMAIL:
  lib/templates/email
WORK_FLOW:
  lib/work_flow/
XML_CONFIG:
  config/config.xml
TEST_CASES:
  lib/test_cases/
Recording:
  lib/record/
WECHAT:
  config/wechat.yaml
LOG:
  report/log/
REPORT:
  report/
CASES_API:
  cases/testcase
TEST_SUITE:
  cases/testsuite
CASES:
  cases/
CASE_DATA:
  data/case_data/
ENV_DATA:
  data/env_data/
RES:
  lib/relevant_params/
